import {supabase,profile,requireAuth,toast,esc,timeAgo,uploadImage} from './database.js';
let me,prof,liked=new Set();
const $=s=>document.querySelector(s);
async function init(){me=await requireAuth();if(!me)return;prof=await profile();if(!prof){await supabase.auth.signOut();return location.href='login.html'}
if(prof.status!=='approved'){ $('#pendingBox').classList.remove('hidden');$('#pendingBox').textContent='حساب شما هنوز توسط مدیر خانواده تأیید نشده است. بعد از تأیید، امکانات خانواده فعال می‌شود.';}
await loadFeed(); setup(); subscribe();}
async function loadFeed(){const {data,error}=await supabase.from('posts').select('*,profiles!posts_author_id_fkey(full_name,avatar_url)').order('created_at',{ascending:false}).limit(50);if(error)return toast(error.message,'error');const feed=$('#feed');feed.innerHTML='';$('#empty').classList.toggle('hidden',!data?.length);
for(const p of data||[]){const {data:l}=await supabase.from('likes').select('user_id').eq('post_id',p.id).eq('user_id',me.id).maybeSingle();if(l)liked.add(p.id);feed.insertAdjacentHTML('beforeend',postHTML(p));}}
function postHTML(p){return `<article class="post card" data-id="${p.id}"><div class="post-head"><div class="avatar">${p.profiles?.avatar_url?`<img src="${p.profiles.avatar_url}">`:'👤'}</div><div><b>${esc(p.profiles?.full_name||'عضو خانواده')}</b><div class="muted small">${timeAgo(p.created_at)}</div></div>${p.author_id===me.id?`<button class="more" data-delete="${p.id}">⋮</button>`:''}</div>${p.content?`<p class="post-text">${esc(p.content).replace(/\n/g,'<br>')}</p>`:''}${p.image_url?`<img class="post-image" src="${p.image_url}" loading="lazy">`:''}<div class="post-actions"><button class="${liked.has(p.id)?'liked':''}" data-like="${p.id}">❤️ <span>${p.like_count||0}</span></button><button data-comments="${p.id}">💬 <span>${p.comment_count||0}</span></button><button data-save="${p.id}">🔖 ذخیره</button></div><div class="comments hidden" id="c-${p.id}"></div><form class="comment-form" data-comment="${p.id}"><input maxlength="500" placeholder="نظر شما..."><button>ارسال</button></form></article>`}
function setup(){$('#postImage').onchange=e=>$('#imageName').textContent=e.target.files[0]?.name||'';$('#publish').onclick=publish;
document.addEventListener('click',async e=>{const like=e.target.closest('[data-like]');if(like)await toggleLike(like.dataset.like);
const com=e.target.closest('[data-comments]');if(com)await toggleComments(com.dataset.comments);
const del=e.target.closest('[data-delete]');if(del&&confirm('این پست حذف شود؟')){const {error}=await supabase.from('posts').delete().eq('id',del.dataset.delete);if(error)toast(error.message,'error');else loadFeed();}
const save=e.target.closest('[data-save]');if(save)toast('ذخیره‌سازی در نسخه بعدی تکمیل می‌شود.');});
document.addEventListener('submit',async e=>{if(!e.target.matches('.comment-form'))return;e.preventDefault();const id=e.target.dataset.comment,input=e.target.querySelector('input');if(!input.value.trim())return;const {error}=await supabase.from('comments').insert({post_id:id,author_id:me.id,content:input.value.trim()});if(error)toast(error.message,'error');else{input.value='';await toggleComments(id,true);}});
$('#searchBtn').onclick=()=>$('#searchBox').classList.toggle('hidden');$('#closeSearch').onclick=()=>$('#searchBox').classList.add('hidden');$('#profileBtn').onclick=()=>location.href='profile.html';$('#notifBtn').onclick=()=>location.href='notifications.html';
$('#searchInput').oninput=search;}
async function publish(){if(prof.status!=='approved')return toast('ابتدا باید توسط مدیر تأیید شوید.','error');const text=$('#postText').value.trim(),file=$('#postImage').files[0];if(!text&&!file)return toast('متن یا عکس اضافه کنید.','error');const b=$('#publish');b.disabled=true;try{let image_url=null;if(file)image_url=await uploadImage(file,`posts/${me.id}`);const {error}=await supabase.from('posts').insert({author_id:me.id,content:text||null,image_url});if(error)throw error;$('#postText').value='';$('#postImage').value='';$('#imageName').textContent='';await loadFeed();toast('پست منتشر شد.','success')}catch(e){toast(e.message,'error')}finally{b.disabled=false}}
async function toggleLike(id){const is=liked.has(id);const q=is?supabase.from('likes').delete().eq('post_id',id).eq('user_id',me.id):supabase.from('likes').insert({post_id:id,user_id:me.id});const {error}=await q;if(error)return toast(error.message,'error');is?liked.delete(id):liked.add(id);const btn=document.querySelector(`[data-like="${id}"]`);if(btn){btn.classList.toggle('liked',!is);const n=btn.querySelector('span');n.textContent=Math.max(0,+n.textContent+(is?-1:1));}}
async function toggleComments(id,force=false){const box=$('#c-'+id);if(!force)box.classList.toggle('hidden');if(box.classList.contains('hidden'))return;const {data}=await supabase.from('comments').select('*,profiles!comments_author_id_fkey(full_name)').eq('post_id',id).order('created_at',{ascending:true});box.innerHTML=(data||[]).map(c=>`<div class="comment"><b>${esc(c.profiles?.full_name||'عضو')}</b><span>${esc(c.content)}</span><small>${timeAgo(c.created_at)}</small></div>`).join('')||'<span class="muted">هنوز نظری نیست.</span>'}
async function search(){const q=$('#searchInput').value.trim();if(q.length<2)return loadFeed();const {data}=await supabase.from('posts').select('*,profiles!posts_author_id_fkey(full_name,avatar_url)').ilike('content','%'+q+'%').order('created_at',{ascending:false});$('#feed').innerHTML=(data||[]).map(postHTML).join('')}
function subscribe(){supabase.channel('posts-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>loadFeed()).subscribe();}
init();
